### ISSUE TITLE
Saving inventory

### ISSUE THREAD

**Issue by Cyrus-Harding** [zcaliptium/gdinv#5]
Is there any prefered or intendend way to save the inventory?

I tried saving it by doing `file.store_val($GDInv_Inventory.STACKS, true)`. But the whole object doesn't get saved, and it gives off errors getting read back.

The only way I found was to keep track of the inventory in a seperate dictionary, but it seems very convoluted to have to keep track of the inventory in a dictionary.

**Comment by rishikiram** [comment]
I have been writing json files which I store in a specified folder that the user must set in the GDInv settings(Project -> Project Settings -> General -> Plugin Setting -> GDInv). The plugin loads all of the json files into the data base when run. The only 'save' is creating these json files. To create the json files I wrote a python script which I run through Terminal on Mac. Hope this helps somewhat

**Comment by Cyrus-Harding** [comment]
@rishikiram I don't think that would work for my usage case.

I have items being add to the inventory, taken out, stacks being deleted and such.

**Comment by Cyrus-Harding** [comment]
My current implimentation works kind of okay. Stuff like having multiple stacks of the same item doesn't work, and breaks.

There has to be a better way of storing STACKS in a file.

**Comment by zcaliptium** [comment]
I didn't wrote any kind of inventory (de)serialization code. I put it on game developer. Because everybody has own game saving system that different from one game to another.

Somebody uses scene nodes saving via ``to_json``, somebody make completelly own system that deals with binary data or dozens of JSONs.

If you really want I can make default implementation of JSON (de)serializing code for the item stacks.

**Comment by zcaliptium** [comment]
I added methods for (de)serializing stack and inventory data as JSONs.

**Comment by Cyrus-Harding** [comment]
Cool.

I'll see if I can implement it soon.
